using Newtonsoft.Json;
using System;
using System.Collections.Generic;

/* Classes that are basically copied from BingusSpeak. These are used to apply the text changes created by the BingusSpeak app */
/* See BingusSpeak repo for more info */
namespace JortPob
{
    // Json serialization container for things
    public class DataDialog
    {
        public List<DataReplacement> replacements;
        public List<DataAddition> additions;
        public DataDialog()
        {
            replacements = new();
            additions = new();
        }
    }

    // Json serialization class for dialog text replacements
    public record DataReplacement
    (
        [JsonConverter(typeof(Common.Int128Converter))] Int128 id, // 64 bit int unique id for a line of dialog, these are generated by the morrowind construction kit and I assume they are consistent through mods and stuff
        string topic, // id for topic this is under
        string text, // original text
        string replacement // replacement text
    );

    // Json serialization class for dialog text additions
    public record DataAddition
    (
        [JsonConverter(typeof(Common.Int128Converter))] Int128 id, // this is the id of the dialog line this was split from. effectively it's origin/parent. when adding new dialog we insert above this id
        string topic, // id for topic this is under
        Dialog.DialogRecord.Type type,
        string speaker,
        string job,
        string faction,
        string cell,
        int rank,
        CharacterContent.Race race,
        CharacterContent.Sex sex,
        string playerFaction,
        int disposition,
        int playerRank,
        List<Dialog.DialogFilter> filters,
        string text,
        string replacement,
        string mp3,
        string script
    );
}
